kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "event-log-collector.fullname" . }}
  annotations:
{{ toYaml .Values.configmap.annotations | indent 4 }}   
  labels:
{{ include "event-log-collector.labels" . | indent 4 }}
data:
  config.yaml: 
    {{ .Values.eventLogCollector.config.content | toYaml | indent 4 }}

{{- if eq .Values.fluentd.enabled true }}
  fluent.conf:
    {{ toYaml .Values.fluentd.service | indent 4 }}
{{- end }}